
version: '3.8'

services:
  flowise:
    image: flowiseai/flowise
    ports:
      - "3000:3000"
    volumes:
      - ~/.flowise:/root/.flowise
    environment:
      - PORT=3000
      - APIKEY_PATH=/root/.flowise
      - DATABASE_PATH=/root/.flowise
    restart: unless-stopped

